export { default as Login } from './Login';
export { default as Register } from './Register';
export { default as Dashboard } from './Dashboard';
export { default as Employees } from './Employees';
export { default as EmployeeDetails } from './EmployeeDetails';
export { default as Profile } from './Profile';
export { default as Settings } from './Settings';
export { default as Reports } from './Reports';
export { default as NotFound } from './NotFound';
